use_frameworks!

platform :ios, '12.0'

target 'SparkCircleProgressView_Example' do
  pod 'SparkCircleProgressView', :path => '../'

  target 'SparkCircleProgressView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
